# This is a generated file. Not intended for manual editing.
services:
  write-off-service:
    build:
      context: "C:\\ASProggs\\InventoryTrack\\src\\Services\\WriteOffService"
      dockerfile: "WriteOffService.Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WriteOffService.Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "writeoffservice.presentation:dev"
    ports: []
    volumes:
    - "C:\\Users\\Алексей\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\ASProggs\\InventoryTrack\\src\\Services\\WriteOffService\\WriteOffService.Presentation:/app:rw"
    - "C:\\ASProggs\\InventoryTrack\\src\\Services\\WriteOffService:/src:rw"
    working_dir: "/app"
