version: '3.8'

services:
  auth-service:
    build:
      context: ./src/Services
      dockerfile: AuthService/AuthService.Presentation/Dockerfile
    ports:
      - "5110:5110"
    environment:
      - ASPNETCORE_URLS=http://+:5110
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConnectionString=Host=auth-db;Port=5432;Database=inventory_track_auth_service;Username=postgres;Password=CHEATS145
    depends_on:
      - auth-db
    networks:
      - inventory-truck-network

  inventory-service:
    build:
      context: ./src/Services
      dockerfile: InventoryService/InventoryService.Presentation/Dockerfile
    ports:
      - "5111:5111"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5111
      - ConnectionStrings__ConnectionString=Host=inventory-db;Port=5432;Database=inventory_track_inventory_service;Username=postgres;Password=CHEATS145
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - inventory-db
      - rabbitmq
    networks:
      - inventory-truck-network

  movement-service:
    build:
      context: ./src/Services
      dockerfile: MovementService/MovementService.Presentation/Dockerfile
    ports:
      - "5112:5112"
    environment:
      - ASPNETCORE_URLS=http://+:5112
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConnectionString=Host=movement-db;Port=5432;Database=inventory_track_movement_service;Username=postgres;Password=CHEATS145
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - movement-db
      - rabbitmq
    networks:
      - inventory-truck-network

  write-off-service:
    build:
      context: ./src/Services
      dockerfile: WriteOffService/WriteOffService.Presentation/Dockerfile
    ports:
      - "5113:5113"
    environment:
      - ASPNETCORE_URLS=http://+:5113
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConnectionString=Host=write-off-db;Port=5432;Database=inventory_track_write_off_service;Username=postgres;Password=CHEATS145
      - RabbitMQ__Hostname=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - write-off-db
      - rabbitmq
    networks:
      - inventory-truck-network

  report-service:
    build:
      context: ./src/Services
      dockerfile: ReportService/ReportService.Presentation/Dockerfile
    ports:
      - "5114:5114"
    environment:
      - ASPNETCORE_URLS=http://+:5114
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://report-db:27017
      - MongoDB__DatabaseName=inventory_track_report_service
    depends_on:
      - report-db
    networks:
      - inventory-truck-network

  auth-db:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHEATS145
      POSTGRES_DB: inventory_track_auth_service
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - inventory-truck-network

  inventory-db:
    image: postgres:15
    container_name: inventory-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHEATS145
      POSTGRES_DB: inventory_track_inventory_service
    volumes:
      - inventory-postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - inventory-truck-network

  movement-db:
    image: postgres:15
    container_name: movement-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHEATS145
      POSTGRES_DB: inventory_track_movement_service
    volumes:
      - movement-postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - inventory-truck-network

  write-off-db:
    image: postgres:15
    container_name: write-off-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHEATS145
      POSTGRES_DB: inventory_track_write_off_service
    volumes:
      - write-off-postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - inventory-truck-network

  report-db:
    image: mongo:5.0
    container_name: report-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CHEATS145
      MONGO_INITDB_DATABASE: inventory_track_report_service
    volumes:
      - report-mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - inventory-truck-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - inventory-truck-network

volumes:
  auth-postgres-data:
  inventory-postgres-data:
  movement-postgres-data:
  write-off-postgres-data:
  report-mongo-data:

networks:
  inventory-truck-network:
    driver: bridge
