# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  auth-service:
    build:
      context: "C:\\ASProggs\\InventoryTrack\\src\\Services\\AuthService"
      dockerfile: "AuthService.Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AuthService.Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "authservice.presentation:dev"
    ports: []
    volumes:
    - "C:\\Users\\Алексей\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\ASProggs\\InventoryTrack\\src\\Services\\AuthService\\AuthService.Presentation:/app:rw"
    - "C:\\ASProggs\\InventoryTrack\\src\\Services\\AuthService:/src:rw"
    working_dir: "/app"
