# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  movement-service:
    build:
      context: "C:\\ASProggs\\InventoryTrack\\src\\Services\\MovementService"
      dockerfile: "MovementService.Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/MovementService.Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "movementservice.presentation:dev"
    ports: []
    volumes:
    - "C:\\Users\\Алексей\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\ASProggs\\InventoryTrack\\src\\Services\\MovementService\\MovementService.Presentation:/app:rw"
    - "C:\\ASProggs\\InventoryTrack\\src\\Services\\MovementService:/src:rw"
    working_dir: "/app"
